### ISSUE TITLE
Mysterious pixel image with wrong `src` attribute

### ISSUE THREAD

**Issue by mstoltenburg** [liveblog/liveblog-amp-theme#17]
https://github.com/liveblog/liveblog-amp-theme/blob/a422ef0f9a0751d58a9fc225df327de981c9c340/templates/template-timeline.html#L50

To make this work it should be written `src="{{ assets_root }}images/image.png"`. I don't know the purpose of that image, but at least the resource is in the repository.

**Comment by tomaszrondio** [comment]
Well, this is ugly hack to make amp images work. There was a bug in AMP js code but it looks like it is fixed now. I removed that unnecessary image.
